name: Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Deploy Environment'
        required: true
        default: 'stag'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          # Private key required to access the host
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          # Hostname or IP to add to the known hosts file
          ssh-host: neutroni.hayo.fi
          
      - name: Print
        run: echo "private"
          echo ${{ secrets.PRIVATE_KEY }}
          echo "hosts"
          echo ${{ secrets.KNOWN_HOSTS }}
          cat ~/.ssh/known_host

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy -v
