name: deploy

on: push

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
     - uses: actions/checkout@v2
     
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: '8.0'
         
     - name: Deploy
       uses: deployphp/action@v1
       with:
         private-key: ${{ secrets.PRIVATE_KEY }}
         known-hosts: ${{ secrets.KNOWN_HOSTS }}       
         dep: deploy
